---
- name: Copy the <<APPLICATION>> systemd service file
  template:
    src: <<APPLICATION>>.service.j2
    dest: /etc/systemd/system/<<APPLICATION>>.service
    owner: root
    group: root
    mode: 0644
  notify: restart <<APPLICATION>>
